# Generated by Django 5.1.2 on 2024-10-21 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizes', '0002_alter_quiz_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quiz',
            old_name='difficluti',
            new_name='difficluty',
        ),
        migrations.AddField(
            model_name='quiz',
            name='number_of_questions',
            field=models.IntegerField(default=1),
        ),
    ]
