# Generated by Django 5.1.2 on 2024-10-22 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizes', '0003_rename_difficluti_quiz_difficluty_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='number_of_questions',
            field=models.IntegerField(default=None),
        ),
    ]
