# Generated by Django 5.1.2 on 2025-03-21 10:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizes', '0004_alter_quiz_number_of_questions'),
    ]

    operations = [
        migrations.CreateModel(
            name='TopicQuiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='quiz',
            name='topic_quiz_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='quizes.topicquiz'),
        ),
    ]
